global class RecordTypes {
	//Last update: 2018-06-11 13:46:58

	//Contact
	global static final String Contact_ContactodeObraSocial = 'Contact-Contacto de Obra Social';
	global static final String Contact_Contactocommunity = 'Contact-Contacto community';
	global static final String Contact_Visitadormedico = 'Contact-Visitador médico';
	global static final String Contact_Contactodesucursal = 'Contact-Contacto de sucursal';
	global static final String Contact_Contactodepaciente = 'Contact-Contacto de paciente';

	//Account
	global static final String Account_Cuentacommunity = 'Account-Cuenta community';
	global static final String Account_GrupodeVisitadoresMedicos = 'Account-Grupo de Visitadores Médicos';
	global static final String Account_Otroprofesional = 'Account-Otro profesional';
	global static final String Account_Cuentaempresa = 'Account-Cuenta empresa';
	global static final String Account_PacienteBestCare = 'Account-Paciente Best Care';
	global static final String Account_PacienteRegular = 'Account-Paciente Regular';
	global static final String Account_Cliente = 'Account-Cliente';
	global static final String Account_Sucursaldefacturacion = 'Account-Sucursal de facturación';
	global static final String Account_Sucursaldeenvio = 'Account-Sucursal de envío';
	global static final String Account_Profesionaldelasalud = 'Account-Profesional de la salud';
	global static final String Account_Visitadormedico = 'Account-Visitador médico';
	global static final String Account_Institucion = 'Account-Institución';
	global static final String Account_Obrasocial = 'Account-Obra social';

	//Formulario
	global static final String Formulario_ChecklistAmbiental = 'Formulario__c-Checklist Ambiental';
	global static final String Formulario_IndicedeKatz = 'Formulario__c-Índice de Katz';
	global static final String Formulario_Evaluacinglobal = 'Formulario__c-Evaluación global subjetiva del estado nutricional';
	global static final String Formulario_Historiaclinicamedica = 'Formulario__c-Historia clínica médica';
	global static final String Formulario_Epicrisis = 'Formulario__c-Epicrisis';
	global static final String Formulario_Historiaclinicadeenfermeria = 'Formulario__c-Historia clínica de enfermería';
	global static final String Formulario_Historiaclinicadeenfermeriadeseguimiento = 'Formulario__c-Historia clínica de enfermería de seguimiento';
	global static final String Formulario_Historiaclinicadeseguimiento = 'Formulario__c-Historia clínica de seguimiento';

	//Task
	global static final String Task_Llamadodeseguimiento = 'Task-Llamado de seguimiento';
	global static final String Task_Tarea = 'Task-Tarea';

	//Interaccion
	global static final String Interaccion_Visitamedica = 'Interaccion__c-Visita médica';
	global static final String Interaccion_Actividadinstitucional = 'Interaccion__c-Actividad institucional';

	//Case
	global static final String Case_Nuevopaciente = 'Case-Nuevo paciente';
	global static final String Case_Acceso = 'Case-Acceso';
	global static final String Case_Psicologico = 'Case-Psicológico';
	global static final String Case_Ventas = 'Case-Ventas';
	global static final String Case_Profesionalesdelasalud = 'Case-Profesionales de la salud';
	global static final String Case_Enviodeproductosc = 'Case-Envío de producto s/c';
	global static final String Case_Otros = 'Case-Otros';
	global static final String Case_Calidad = 'Case-Calidad';
	global static final String Case_Servicio = 'Case-Servicio';
	global static final String Case_Insumos = 'Case-Insumos';
	global static final String Case_Comerciales = 'Case-Comerciales';
	global static final String Case_Nutricionales = 'Case-Nutricionales';
	global static final String Case_Devolucion = 'Case-Devolución';
	global static final String Case_Diferencia = 'Case-Diferencia';
	global static final String Case_Varios = 'Case-Varios';
	global static final String Case_Redessociales = 'Case-Redes sociales';

	//Tratamiento
	global static final String Tratamiento_TratamientoBestCare = 'Tratamiento__c-Tratamiento Best Care';
	global static final String Tratamiento_TratamientoRegular = 'Tratamiento__c-Tratamiento Regular';
}