global class RecordTypes {
	//Last update: 2021-09-06 04:42:49

	//Order
	global static final String Order_Dan360PedidoVentaDirecta = 'Order-Dan360_PedidoVentaDirecta';
	global static final String Order_Dan360PedidoSinCargo = 'Order-Dan360_PedidoSinCargo';

	//Account
	global static final String Account_Institucion = 'Account-Institucion';
	global static final String Account_PersonAccount = 'Account-PersonAccount';
	global static final String Account_ProfesionaldelaSalud = 'Account-Profesional_de_la_Salud';
	global static final String Account_OtroProfesional = 'Account-Otro_Profesional';

	//Dan360Matricula
	global static final String Dan360Matricula_Nacional = 'Dan360_Matricula__c-Nacional';
	global static final String Dan360Matricula_Provincial = 'Dan360_Matricula__c-Provincial';
	global static final String Dan360Matricula_Municipal = 'Dan360_Matricula__c-Municipal';

	//Dan360Licencia
	global static final String Dan360Licencia_Licencia = 'Dan360_Licencia__c-Licencia';
	global static final String Dan360Licencia_TiemponoPromocional = 'Dan360_Licencia__c-Tiempo_no_Promocional';

	//Knowledgekav
	global static final String Knowledgekav_FAQ = 'Knowledge__kav-FAQ';
	global static final String Knowledgekav_Procedure = 'Knowledge__kav-Procedure';
}